# Generated by Django 2.1.2 on 2018-10-30 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import organizer.array
import organizer.soillayer
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weather', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OPD',
            fields=[
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('solarhour', models.CharField(default='12.0', editable=False, max_length=10)),
                ('name', models.CharField(blank=True, help_text='Name this model run', max_length=30, verbose_name='Name of run')),
                ('nrun', models.CharField(blank=True, default='7300', help_text='(days): Number of simulation days', max_length=10, verbose_name='Simulation days')),
                ('seed', models.CharField(blank=True, default='965745566761', help_text='Seed for random number generator (-ve for random, +ve for deterministic)', max_length=15, verbose_name='Seed')),
                ('lat', models.CharField(blank=True, default='2.253213', help_text='(deg.): Site latitude (+ve for North; -ve for South)', max_length=10, verbose_name='Site latitude')),
                ('methgt', models.CharField(blank=True, default='2.0', help_text='(m): Height from ground', max_length=10, verbose_name='Weather station height')),
                ('doy', models.CharField(blank=True, default='1', help_text='(day): Start of simulation (Jan. 1 = 1, ... Dec. 31 = 365', max_length=10, verbose_name='Initial day of year')),
                ('dewtemp', models.CharField(blank=True, default='23.0', help_text='(°C): Dew point air temperature', max_length=10, verbose_name='Dew point temperature')),
                ('lag', models.CharField(blank=True, default='1.5', help_text='(hours): No. of hours after sunrise when air temperature is minimum', max_length=10, verbose_name='No. of lag hours')),
                ('is_generated', models.CharField(choices=[('F', 'Use weather file'), ('S', 'Simulate weather')], default='S', help_text='Source of the daily weather data', max_length=1, verbose_name='Weather data source')),
                ('tmin_mean', models.CharField(blank=True, default='23.823', help_text='(°C): Annual average of min. air temperature', max_length=10, verbose_name='Annual average')),
                ('tmin_amp', models.CharField(blank=True, default='0.612', help_text='(°C): Difference between the highest air temperature and the annual average min. air temperature', max_length=10, verbose_name='Amplitude of average')),
                ('tmin_cv', models.CharField(blank=True, default='0.008', help_text='(°C): Annual average monthly CV (coefficient of variation)', max_length=10, verbose_name='CV')),
                ('tmin_ampcv', models.CharField(blank=True, default='-0.006', help_text='(°C): Difference between the lowest and annual average monthly CV', max_length=10, verbose_name='Amplitude of CV')),
                ('tmin_meanwet', models.CharField(blank=True, default='23.823', help_text='(°C): Annual average min. air temperature for only wet days', max_length=10, verbose_name='Annual average for wet days')),
                ('tmax_mean', models.CharField(blank=True, default='31.837', help_text='(°C): Annual average of max. air temperature', max_length=10, verbose_name='Annual average')),
                ('tmax_amp', models.CharField(blank=True, default='0.798', help_text='(°C): Difference between the highest air temperature and the annual average max. air temperature', max_length=10, verbose_name='Amplitude of average')),
                ('tmax_cv', models.CharField(blank=True, default='0.009', help_text='(°C): Annual average monthly CV (coefficient of variation)', max_length=10, verbose_name='CV')),
                ('tmax_ampcv', models.CharField(blank=True, default='-0.007', help_text='(°C): Difference between the lowest and annual average monthly CV', max_length=10, verbose_name='Amplitude of CV')),
                ('tmax_meanwet', models.CharField(blank=True, default='31.837', help_text='(°C): Annual average max. air temperature for only wet days', max_length=10, verbose_name='Annual average for wet days')),
                ('rain_pww', organizer.array.Array12ModelField(blank=True, default=['Month', 'P(W|W)', 'Jan', '0.64', 'Feb', '0.45', 'Mar', '0.49', 'Apr', '0.46', 'May', '0.50', 'Jun', '0.54', 'Jul', '0.51', 'Aug', '0.55', 'Sep', '0.60', 'Oct', '0.71', 'Nov', '0.82', 'Dec', '0.80'], help_text='^(0-1): Probability of having 2 wet (W) days in succession', verbose_name='P(W|W)')),
                ('rain_pwd', organizer.array.Array12ModelField(blank=True, default=['Month', 'P(W|D)', 'Jan', '0.39', 'Feb', '0.20', 'Mar', '0.24', 'Apr', '0.21', 'May', '0.25', 'Jun', '0.29', 'Jul', '0.26', 'Aug', '0.30', 'Sep', '0.35', 'Oct', '0.46', 'Nov', '0.57', 'Dec', '0.55'], help_text='^(0-1): Probability of having a dry (D) then wet (W) day', verbose_name='P(W|D)')),
                ('rain_shape', organizer.array.Array12ModelField(blank=True, default=['Month', 'α', 'Jan', '0.95'], help_text='^(-): Shape factor α of the gamma probability distribution', verbose_name='Shape factor')),
                ('rain_scale', organizer.array.Array12ModelField(blank=True, default=['Month', 'β', 'Jan', '16.39'], help_text='^(mm): Scale factor β of the gamma probability distribution', verbose_name='Scale factor')),
                ('wind_shape', organizer.array.Array12ModelField(blank=True, default=['Month', 'k', 'Jan', '1.595'], help_text='^(-): Shape factor k of the Weibull distribution', verbose_name='Shape factor')),
                ('wind_scale', organizer.array.Array12ModelField(blank=True, default=['Month', 'λ', 'Jan', '2.578'], help_text='^(m/s): Scale factor λ of the Weibull distribution', verbose_name='Scale factor')),
                ('treeage', models.CharField(blank=True, default='365', help_text='(days): Tree/palm age at start of simulation', max_length=10, verbose_name='Initial tree age')),
                ('plantdens', models.CharField(blank=True, default='148', help_text='(palms/ha): No. of trees per ha', max_length=10, verbose_name='Planting density')),
                ('thinplantdens', models.CharField(blank=True, default='-1', help_text='(palms/ha): Planting density after thinning (-ve value for no thinning)', max_length=10, verbose_name='Thinning planting density')),
                ('thinage', models.CharField(blank=True, default='3650', help_text='(days): Age of tree for thinning (ignored if thinning planting density is -ve)', max_length=10, verbose_name='Age of tree for thinning')),
                ('femaleprob', models.CharField(blank=True, default='0.5', help_text='(0-1): Probability of producing female flowers', max_length=10, verbose_name='Probability of female flowers')),
                ('pinnae_wgt', models.CharField(blank=True, default='0.4', help_text='(kg/palm): Initial dry weight of pinnae', max_length=10, verbose_name='Pinnae weight')),
                ('rachis_wgt', models.CharField(blank=True, default='0.7', help_text='(kg/palm): Initial dry weight of rachis', max_length=10, verbose_name='Rachis weight')),
                ('trunk_wgt', models.CharField(blank=True, default='0.1', help_text='(kg/palm): Initial dry weight of trunk', max_length=10, verbose_name='Trunk weight')),
                ('roots_wgt', models.CharField(blank=True, default='0.2', help_text='(kg/palm): Initial dry weight of roots', max_length=10, verbose_name='Roots weight')),
                ('maleflo_wgt', models.CharField(blank=True, default='0.0', help_text='(kg/palm): Initial dry weight of male flowers', max_length=10, verbose_name='Male flowers weight')),
                ('femaflo_wgt', models.CharField(blank=True, default='0.0', help_text='(kg/palm): Initial dry weight of female flowers', max_length=10, verbose_name='Female flowers weight')),
                ('bunches_wgt', models.CharField(blank=True, default='0.0', help_text='(kg/palm): Initial dry weight of bunches', max_length=10, verbose_name='Bunches weight')),
                ('pinnae_n', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.026', '426', '0.0204', '883', '0.0182', '1218', '0.0196', '1583', '0.0202', '1948', '0.0188', '2313', '0.0211', '2739', '0.0193', '3135', '0.0198', '3500', '0.0208', '3866', '0.019', '4170', '0.0204', '4809', '0.0206', '5266', '0.0212', '5601', '0.0214', '11500', '0.02'], help_text='^N fraction in pinnae vs. palm age (days)', verbose_name='Pinnae N')),
                ('pinnae_m', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.03917', '426', '0.02186', '883', '0.01854', '1218', '0.01862', '1583', '0.01753', '1948', '0.01805', '2313', '0.01719', '2739', '0.01628', '3135', '0.01643', '3500', '0.016', '3866', '0.0172', '4170', '0.01564', '4809', '0.01597', '5266', '0.01603', '5601', '0.01486', '11500', '0.015'], help_text='^Minerals fraction in pinnae vs. palm age (days)', verbose_name='Pinnae minerals')),
                ('rachis_n', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.0059', '426', '0.00423', '883', '0.00421', '1218', '0.00383', '1583', '0.0035', '1948', '0.00335', '2313', '0.00325', '2739', '0.00383', '3135', '0.00361', '3500', '0.00292', '3866', '0.00346', '4170', '0.0034', '4809', '0.00368', '5266', '0.00426', '5601', '0.00448', '11500', '0.00448'], help_text='^N fraction in rachis vs. palm age (days)', verbose_name='Rachis N')),
                ('rachis_m', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.01854', '426', '0.01399', '883', '0.01721', '1218', '0.02072', '1583', '0.01722', '1948', '0.02082', '2313', '0.01939', '2739', '0.01501', '3135', '0.01808', '3500', '0.01829', '3866', '0.02032', '4170', '0.01503', '4809', '0.01503', '5266', '0.01503', '5601', '0.01595', '11500', '0.0177'], help_text='^Minerals fraction in rachis vs. palm age (days)', verbose_name='Rachis minerals')),
                ('roots_n', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.0107', '883', '0.00498', '2313', '0.00326', '3866', '0.00342', '5266', '0.00285', '11500', '0.002'], help_text='^N fraction in roots vs. palm age (days)', verbose_name='Roots N')),
                ('roots_m', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.021', '883', '0.0157', '2313', '0.0133', '3866', '0.0124', '5266', '0.0231', '11500', '0.02'], help_text='^Minerals fraction in roots vs. palm age (days)', verbose_name='Roots minerals')),
                ('trunk_n', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.0101', '426', '0.00707', '883', '0.00955', '1218', '0.00825', '1583', '0.00685', '1948', '0.00742', '2313', '0.00574', '2739', '0.0071', '3135', '0.00753', '3500', '0.00509', '3866', '0.00459', '4170', '0.00631', '4809', '0.0048', '5266', '0.00483', '5601', '0.00492', '11500', '0.004'], help_text='^N fraction in trunk vs. palm age (days)', verbose_name='Trunk N')),
                ('trunk_m', organizer.array.Array16ModelField(blank=True, default=['Age', 'Fraction', '0', '0.0176', '426', '0.0166', '883', '0.0308', '1218', '0.0351', '1583', '0.0349', '1948', '0.0351', '2313', '0.0285', '2739', '0.0259', '3135', '0.0231', '3500', '0.0232', '3866', '0.0285', '4170', '0.0172', '4809', '0.028', '5266', '0.0238', '5601', '0.0156', '11500', '0.015'], help_text='^Minerals fraction in trunk vs. palm age (days)', verbose_name='Trunk minerals')),
                ('sla', organizer.array.Array16ModelField(blank=True, default=['Age', 'SLA', '0', '13.20', '365', '13.20', '840', '7.25', '4234', '7.25', '6169', '7.25', '7300', '7.25', '11500', '7.25'], help_text='^Specific leaf area (SLA) (m2/kg) vs. palm age (days)', verbose_name='SLA')),
                ('co2ambient', models.CharField(blank=True, default='-1987', help_text='(µmol/mol or year): Atmospheric concentration of CO2 (+ve for actual value or -ve for year)', max_length=10, verbose_name='Initial ambient CO2')),
                ('co2change', models.CharField(blank=True, default='1.7', help_text='(µmol/mol/yr): Annual change in atmospheric CO2 concentration', max_length=10, verbose_name='Change in ambient CO2')),
                ('refhgt', models.CharField(blank=True, default='23.0', help_text='(m): Height from ground', max_length=10, verbose_name='Reference height')),
                ('numintervals', models.CharField(blank=True, default='100', help_text='No. of subintervals in a day for daily integration', max_length=10, verbose_name='No of subintervals')),
                ('rootdepth', models.CharField(blank=True, default='0.2', help_text='(m): Depth of roots below the soil surface', max_length=10, verbose_name='Initial rooting depth')),
                ('has_watertable', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', help_text='Select "Yes" if there is a water table and it is just below the last soil layer', max_length=1, verbose_name='Any water table?')),
                ('numlayers', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default='3', help_text='Min: 2 layers, Max: 6 layers', max_length=1, verbose_name='No. of soil layers')),
                ('layer1', organizer.soillayer.SoilLayerModelField(blank=True, default=['0.05', '-2', '25.0', '70.0', '2.0'], help_text='^Soil properties', verbose_name='Soil Layer 1')),
                ('layer2', organizer.soillayer.SoilLayerModelField(blank=True, default=['0.55', '-2', '29.0', '66.0', '1.5'], help_text='^Soil properties', verbose_name='Soil Layer 2')),
                ('layer3', organizer.soillayer.SoilLayerModelField(blank=True, default=['0.90', '-2', '29.0', '66.0', '0.0'], help_text='^Soil properties', verbose_name='Soil Layer 3')),
                ('layer4', organizer.soillayer.SoilLayerModelField(blank=True, default=['0.25', '-2', '50.0', '25.0', '0.0'], help_text='^Soil properties', verbose_name='Soil Layer 4')),
                ('layer5', organizer.soillayer.SoilLayerModelField(blank=True, default=['0.25', '-2', '50.0', '25.0', '0.0'], help_text='^Soil properties', verbose_name='Soil Layer 5')),
                ('layer6', organizer.soillayer.SoilLayerModelField(blank=True, default=['0.25', '-2', '50.0', '25.0', '0.0'], help_text='^Soil properties', verbose_name='Soil Layer 6')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('weatherfilename', models.ForeignKey(blank=True, help_text='Filename of the daily weather data', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opd', to='weather.Weather', verbose_name='Weather filename')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
