"""
Django settings for pysawitweb project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
from decouple import config
from django.urls import reverse_lazy


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = ['www.pysawitweb.com', '127.0.0.1']

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contact',
    'weather',
    'organizer',
    'user',
    'django.contrib.sites.apps.SitesConfig',
    'django.contrib.humanize.apps.HumanizeConfig',
    'django_nyt.apps.DjangoNytConfig',
    'mptt',
    'sekizai',
    'sorl.thumbnail',
    'wiki.apps.WikiConfig',
    'wiki.plugins.attachments.apps.AttachmentsConfig',
    'wiki.plugins.notifications.apps.NotificationsConfig',
    'wiki.plugins.images.apps.ImagesConfig',
    'wiki.plugins.macros.apps.MacrosConfig',

    'django_otp',
    'django_otp.plugins.otp_totp',
    'django_otp.plugins.otp_hotp',
    'django_otp.plugins.otp_static',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',

    'django_otp.middleware.OTPMiddleware',
    'django_referrer_policy.middleware.ReferrerPolicyMiddleware',
]

PYTHONANYWHERE = config('PYTHONANYWHERE', default=False, cast=bool)

ROOT_URLCONF = 'pysawitweb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'sekizai.context_processors.sekizai',
            ],
        },
    },
]

WSGI_APPLICATION = 'pysawitweb.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': config('DB_ENGINE'),
        'NAME': os.path.join(BASE_DIR, config('DB_NAME')),
    }
}

LOG_TO_FILE = config('LOG_TO_FILE', default=False, cast=bool)

if LOG_TO_FILE:
    from .log_filters import ManagementFilter
    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'filters': {
            'remove_migration_sql': {
                '()': ManagementFilter,
            },
        },
        'formatters': {
            'verbose': {
                'format': "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
                'datefmt': "%d/%b/%Y %H:%M:%S"
            },
            'simple': {
                'format': '%(levelname)s %(message)s'
            },
        },
        'handlers': {
            'file': {
                'level': 'DEBUG',
                'filters': ['remove_migration_sql'],
                'class': 'logging.FileHandler',
                'filename': 'debug.log',
                'formatter': 'verbose'
            },
        },
        'loggers': {
            'django': {
                'handlers': ['file'],
                'propagate': True,
                'level': 'DEBUG',
            },
            'MYAPP': {
                'handlers': ['file'],
                'level': 'DEBUG',
            },
        }
    }

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8, }
     },
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator', },
    {'NAME': 'user.validators.NumberValidator',
        'OPTIONS': {
            'min_digits': 1, }},
    {'NAME': 'user.validators.UppercaseValidator', },
    {'NAME': 'user.validators.LowercaseValidator', },
    {'NAME': 'user.validators.SymbolValidator', },
]


# Send Email
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = True


# Receive Email
SERVER_EMAIL = config('SERVER_EMAIL')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')
EMAIL_SUBJECT_PREFIX = '[PySawit Web] '
MANAGERS = (
    ('Us', config('MANAGERS_US')),
)

# DJANGO MESSAGES + BOOTSTRAP ALERT
PYSW_INFO = 100
PYSW_SUCCESS = 101
PYSW_WARNING = 102
PYSW_ERROR = 103

MESSAGE_TAGS = {
    PYSW_INFO: 'alert-info',
    PYSW_SUCCESS: 'alert-success',
    PYSW_WARNING: 'alert-warning',
    PYSW_ERROR: 'alert-danger',
}

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TIME_ZONE = 'Asia/Kuala_Lumpur'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/
STATIC_URL = '/static/'

if PYTHONANYWHERE:
    STATIC_ROOT = "/home/cbsteh/pysawitweb/static"
else:
    STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]

# MEDIA
MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# LOGIN
LOGIN_REDIRECT_URL = reverse_lazy('organizer_opd_list')

LOGIN_URL = reverse_lazy('dj-auth:login')

LOGOUT_URL = reverse_lazy('dj-auth:logout')

# reCAPTCHA
GOOGLE_RECAPTCHA_SECRET_KEY = config('GOOGLE_RECAPTCHA_SECRET_KEY')

# WIKI
SITE_ID = 1

WIKI_ACCOUNT_HANDLING = False

NYT_EMAIL_SENDER = 'no-reply@pysawitweb.com'

WIKI_MARKDOWN_KWARGS = {
    'extensions': [
        'markdown.extensions.footnotes',
        'markdown.extensions.fenced_code',
        'markdown.extensions.tables',
        'mdx_del_ins',
        'mdx_subscript',
        'mdx_superscript',
    ],
}

WIKI_MARKDOWN_HTML_WHITELIST = ['sub', 'ins', 'del']

# Deploying to Pythonanywhere host
if PYTHONANYWHERE:
    CSRF_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'Strict'
    SESSION_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_SSL_REDIRECT = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 300
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# django-referrer-policy
REFERRER_POLICY = 'no-referrer-when-downgrade'
