# Generated by Django 2.1.2 on 2018-10-30 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import weather.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, help_text='Brief description of this weather file', max_length=255, verbose_name='Description')),
                ('weatherfile', models.FileField(blank=True, help_text='Name of weather file to use', upload_to=weather.models.user_folder_path, verbose_name='Weather file')),
                ('repofile', models.CharField(blank=True, max_length=255)),
                ('nasafile', models.CharField(blank=True, max_length=255)),
                ('nasa_tfile', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['weatherfile'],
            },
        ),
    ]
