# Generated by Django 2.1.2 on 2018-10-30 05:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181030_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='C:\\Users\\cbste\\Dropbox\\pysawitweb\\media/repository/images/anon.png', help_text='Upload your profile photo', upload_to=user.models.user_avatar_path, verbose_name='Profile photo'),
        ),
    ]
