# Generated by Django 2.1.2 on 2018-10-30 07:27

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20181030_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(help_text='Upload your profile photo', upload_to=user.models.user_avatar_path, verbose_name='Profile photo'),
        ),
    ]
