# Generated by Django 2.1.2 on 2018-10-30 07:32

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20181030_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your profile photo', null=True, upload_to=user.models.user_avatar_path, verbose_name='Profile photo'),
        ),
    ]
