# Generated by Django 2.1.2 on 2018-10-30 09:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20181030_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload your profile photo', upload_to=user.models.user_avatar_path, verbose_name='Profile photo'),
        ),
    ]
