# Generated by Django 2.1.2 on 2018-10-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181030_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_avatar',
            field=models.BooleanField(default='False', help_text='Do you wish to have a profile photo?', verbose_name='Any profile photo?'),
        ),
    ]
