# Generated by Django 2.1.2 on 2018-10-31 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_userprofile_has_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_avatar',
        ),
    ]
